### ISSUE TITLE
Runtime error 216 on modern Windows

### ISSUE THREAD

**Issue by VedVid** [devapromix-roguelikes/troll-hunter#1]
My primary platform is Windows 10 64-bit and that runtime error triggers for every release. Although everything works well on older Windows XP 32-bit.

**Comment by devapromix** [comment]
The game runs only on Windows XP 32.

**Comment by VedVid** [comment]
Just tested latest (ie 0.12.1) release, using Windows 10 x64, and it works like a charm now.

**Comment by devapromix** [comment]
Thanks for the test.
