### ISSUE TITLE
Crash on exit game

### ISSUE THREAD

**Issue by VedVid** [devapromix-roguelikes/troll-hunter#2]
After confirming decision to exit game, Trollhunter, error message appears.

https://imgur.com/a/eX8i4

Details are supposed to stored in 4c81_appcompat.txt withing a Temp directory, but I can't find it.

It's true for 0.10.1, 0.9, 0.8. Release 0.7 crashes on exit with *The instruction at "0x7c90100b" referenced memory at "0x00001078". The memory could not be "read".*

Tested on Windows XP 32-bit

**Comment by devapromix** [comment]
Hello! I will try to find and fix this error.

**Comment by VedVid** [comment]
This crash remains in 0.12.1 release. Does anybody else encounter that issue too?

Somewhat I cant attach log.txt directly, so I used pastebin: [log.txt](https://pastebin.com/7w22YktC)

**Comment by devapromix** [comment]
Perhaps the bug will be fixed in the next version.

**Comment by VedVid** [comment]
Just tested 0.13.1 release. Game is not crashing anymore.

**Comment by devapromix** [comment]
It's good.
