### ISSUE TITLE
Cannot find Libc used by GNUGetText

### ISSUE THREAD

**Issue by eugeneloza** [devapromix-roguelikes/troll-hunter#3]
Trying to compile Trollhunter.lpi in Lazarus/Debian Linux:

> GNUGetText.pas(270,3) Fatal: Cannot find Libc used by GNUGetText of the Project Inspector.

Followed by a lot of other (maybe, related) errors.

**Comment by devapromix** [comment]
Hi! Slightly corrected the module GNUGetText and fixed bugs. Sources compiles in Lazarus IDE.
