### ISSUE TITLE
The application was unable to start correctly 0xc000007b

### ISSUE THREAD

**Issue by eugeneloza** [devapromix-roguelikes/troll-hunter#7]
Couldn't run the game with Lazarus/fpc trunk (the compilation is successful) under Windows 7x64. I wonder what this error means?
![scrot](https://user-images.githubusercontent.com/10726162/35180844-aa6116d6-fdc0-11e7-9419-40d99a16ec7c.png)

**Comment by devapromix** [comment]
It is necessary to replace the BearLibTerminal with a 64 bit version.

**Comment by eugeneloza** [comment]
Thanks it's working!
